# Generated by Django 3.1 on 2024-01-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191114_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_morrisons',
            new_name='price_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_sainsburys',
            new_name='price_flipkart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_tesco',
            new_name='price_snapdeal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_morrisons',
            new_name='url_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_sainsburys',
            new_name='url_flipkart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_tesco',
            new_name='url_snapdeal',
        ),
    ]
